# Declare sounds used by this game.

# define sound effects & music
label sounds:
    # define blip = "audio/sfx/blip.ogg"
    define attchoice = "audio/sfx/orex_ui_attraction.ogg"
    define decchoice = "audio/sfx/orex_ui_decay.ogg"
    define attdecchoice = "audio/sfx/orex_ui_decayattraction.ogg"
    define clock = "audio/sfx/clock.ogg"
    define train = "audio/sfx/train.ogg"
    define glassclink = "audio/sfx/glassclink.ogg"
    define twinkle = "audio/sfx/twinkle.ogg"
    define horror = "audio/sfx/horror.ogg"
    define writing = "audio/sfx/writing.ogg"
    define shuffle = "audio/sfx/shuffle.ogg"
    define darts = "audio/sfx/darts.ogg"
    define cooking = "audio/sfx/cooking.ogg"
    define dining = "audio/sfx/dining.ogg"
    define teleport = "audio/sfx/teleport.ogg"
    define swoosh = "audio/sfx/swoosh.ogg"
    define heartbeat = "audio/sfx/heartbeat.ogg"
    define sigh = "audio/sfx/sigh.ogg"
    define furniture = "audio/sfx/furniture.ogg"
    # define scoff = "audio/sfx/scoff.ogg"
    # define laugh = "audio/sfx/laugh.ogg"
    define windowopen = "audio/sfx/windowopen.ogg"
    define windowshut = "audio/sfx/windowshut.ogg"
    define crash = "audio/sfx/crash.ogg"
    define trainwhistle = "audio/sfx/trainwhistle.mp3"
    define snap = "audio/sfx/snap.ogg"
    define knock = "audio/sfx/knock.ogg"
    define gasp = "audio/sfx/gasp.ogg"
    define footsteps = "audio/sfx/footsteps.ogg"
    define doorslam = "audio/sfx/doorslam.ogg"

    return
